version: "3.8"

services:
  database:
    image: postgres:13.16-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: user # Set your database username
      POSTGRES_PASSWORD: password # Set your database password
      POSTGRES_DB: brotherhood-db # Set your database name
    ports:
      - "5432:5432" # Expose the PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data # Mount the volume to persist data

volumes:
  db_data:
    driver: local
